### ISSUE TITLE
Missing documentation on panics

### ISSUE THREAD

**Issue by wolthom** [blyxxyz/lexopt#17]
Hey there,

First off, fantastic work with this crate! I really enjoy the interface and how lightweight it is!

While playing around with `lexopt`, I noticed that the following tiny example produced a panic that stumped me quite a bit:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut parser = lexopt::Parser::from_env();
    while let Some(arg) = parser.next()? {
        dbg!(arg);
    }
    Ok(())
}
```

When running this example as `cargo run -- --m 10`, everything works fine.
However, if I run this as `cargo run -- --m=10`, the code panics.
When consuming the value in the body of the `while` loop (via `parser.optional_value()`), the example works again.

Is this behavior expected / documented somewhere? It did surprise me quite a bit.

**Comment by blyxxyz** [comment]
Thanks for checking it out! I think that what you're seeing is not a panic but rather a regular error, returned by `parser.next()`, documented [here](https://docs.rs/lexopt/0.2.1/lexopt/struct.Parser.html#errors). This is the output I get, for reference:
```
[src/main.rs:4] arg = Short(
    'm',
)
Error: unexpected argument for option '-m': "10"
```

The parser expects you to finish handling `-m` before you call `.next()` again, so if you didn't call a method like `.value()` or `.optional_value()` then it assumes `-m` doesn't take a value and reports an error.

**Comment by wolthom** [comment]
Argh, this is embarassing! You're right of course, the panic comes stems from me bubbling the error up via `?`.

So to clarify my understanding:
The presence of `=` (e.g. in `-m=10` or `--number=10`) signifies an option with an attached value.

In contrast, `-m 10` or `--number 10` would signify a flag followed by a standalone value?

**Comment by blyxxyz** [comment]
In `-m 10`, `10` is either a standalone argument or a value for `-m`, depending on whether you call `parser.value()` after seeing the option. If you get `Short('m')`, and then call `parser.value()`, it returns `Ok("10")`.

You can compare it to other commands, like `tail`. If you run `tail -n 10 /etc/hosts` then it thinks `10` is the number of lines (because `-n` takes a value), but if you run `tail -q 10 /etc/hosts` it thinks `10` is a filename (because `-q` doesn't take a value).

`parser.optional_value()` is for hybrid options that *sometimes* take a value, like GNU sed's `-i` option. But this is pretty uncommon, it's better to experiment with `parser.value()` instead.

The README isn't particularly clear on this, so maybe I'll tweak it a bit.

**Comment by blyxxyz** [comment]
Anyway, thanks again for reaching out! I don't always have a good view of how people use the library, so this was helpful.

**Comment by wolthom** [comment]
You're very welcome!

Also thanks a lot for your time and help :)
The behavior definitely does make sense and is very flexible. I could've spent a bit more time experimenting and things probably would've clicked by themselves as well!
