### ISSUE TITLE
Short options should be able to take value with format -o=v

### ISSUE THREAD

**Issue by theIDinside** [blyxxyz/lexopt#8]
Would be nice to be able to say ```-o=some_value``` to adhere more closely to standards and other libraries / crates and thus make the switch away from more "heavy" libraries to this one a much more pleasant experience. For those who wish to have compilation speed and much less bloat, this would make that move much easier and not justifying the move much harder.

**Comment by blyxxyz** [comment]
I think I mainly left it out because I wasn't used to it and found it weird. I also figured that leaving it out would make `-x"$FOO"` slightly more reliable (if `$FOO` starts with `=`), but it already fails if `$FOO` is empty so that's silly.

GNU getopt doesn't support it, but Python's argparse does. I think you're right, I'll implement it.
